module TailwindExtra exposing
    ( bg_black_50
    , bg_brand_10
    , bg_brand_15
    , bg_brand_20
    , bg_brand_5
    , bg_brand_red_10
    , bg_brand_red_15
    , bg_brand_yellow_20
    , bg_current
    , bg_transparent
    , border_black_10
    , border_brand_30
    , border_brand_40
    , border_t_brand
    , border_t_gray_900
    , border_transparent
    , border_white_10
    , divide_color
    , grid_cols_auto_1fr
    , group
    , h_35
    , inset_0
    , inset_y_0
    , leading_10
    , leading_6
    , leading_7
    , left_0
    , left_0_5
    , left_2
    , left_half
    , li_before_content_check
    , li_before_text_brand_yellow
    , li_flex
    , li_gap_2
    , li_items_center
    , max_w_2xl
    , max_w_3xl
    , max_w_4xl
    , max_w_5xl
    , max_w_7xl
    , max_w_lg
    , ms_12
    , ms_8
    , neg_start_6
    , neg_translate_x_half
    , not_prose
    , p_my_0
    , p_text_inherit
    , peer
    , right_2
    , ring_brand
    , ring_brand_yellow
    , scroll_mt
    , space_y
    , text_brand_50
    , text_brand_70
    , text_brand_80
    , text_white_50
    , text_white_60
    , text_white_70
    , text_white_80
    , text_white_90
    , top_0
    , top_0_5
    , top_2
    , translate_x_0
    , translate_x_5
    , type_body
    , type_body_small
    , type_caption
    , type_display
    , type_h1
    , type_h2
    , type_h3
    , type_h4
    , type_mono
    , type_overline
    , ul_list_none
    , ul_my_0
    , ul_pl_0
    , ul_space_y_2
    , w_35
    )

{-| Typed Tailwind helpers for utilities not yet generated by elm-tailwind-classes.

These fill the gaps left by the auto-generated `Tailwind` module. Each function
uses the `Tailwind` constructor directly (no `Tw.raw`) so the `LlmAgent.NoTailwindRawStrings`
elm-review rule stays green and the elm-tailwind-classes extractor can still
find the class strings statically.

When elm-tailwind-classes adds support for these utilities natively, migrate
callers to the generated versions and delete the corresponding function here.

-}

import Tailwind exposing (Tailwind(..))
import Tailwind.Theme exposing (Color, Spacing, colorToString, spacingToString)


{-| Adds vertical space between child elements.

    TailwindExtra.space_y Th.s4 -- "space-y-4"

-}
space_y : Spacing -> Tailwind
space_y spacing =
    Tailwind ("space-y-" ++ spacingToString spacing)


{-| Scroll margin-top — offsets a sticky header when anchor-linking to a section.

    TailwindExtra.scroll_mt Th.s28 -- "scroll-mt-28"

-}
scroll_mt : Spacing -> Tailwind
scroll_mt spacing =
    Tailwind ("scroll-mt-" ++ spacingToString spacing)


{-| Colour the divider lines produced by `divide-y` / `divide-x`.

    TailwindExtra.divide_color (Th.gray Th.s100) -- "divide-gray-100"

-}
divide_color : Color -> Tailwind
divide_color color =
    Tailwind ("divide-" ++ colorToString color)


{-| Caps width at Tailwind's `2xl` container size (42 rem / 672 px).
-}
max_w_2xl : Tailwind
max_w_2xl =
    Tailwind "max-w-2xl"


{-| Caps width at Tailwind's `3xl` container size (48 rem / 768 px).
-}
max_w_3xl : Tailwind
max_w_3xl =
    Tailwind "max-w-3xl"


{-| Caps width at Tailwind's `4xl` container size (56 rem / 896 px).
-}
max_w_4xl : Tailwind
max_w_4xl =
    Tailwind "max-w-4xl"


{-| Caps width at Tailwind's `5xl` container size (64 rem / 1024 px).
-}
max_w_5xl : Tailwind
max_w_5xl =
    Tailwind "max-w-5xl"


{-| Caps width at Tailwind's `7xl` container size (80 rem / 1280 px).
-}
max_w_7xl : Tailwind
max_w_7xl =
    Tailwind "max-w-7xl"


{-| Caps width at Tailwind's `lg` container size (32 rem / 512 px).
-}
max_w_lg : Tailwind
max_w_lg =
    Tailwind "max-w-lg"


{-| White text at 50 % opacity.
-}
text_white_50 : Tailwind
text_white_50 =
    Tailwind "text-white/50"


{-| White text at 60 % opacity.
-}
text_white_60 : Tailwind
text_white_60 =
    Tailwind "text-white/60"


{-| White text at 70 % opacity.
-}
text_white_70 : Tailwind
text_white_70 =
    Tailwind "text-white/70"


{-| White text at 80 % opacity — used for navbar links on a dark background.

Tailwind opacity-modifier syntax (`text-white/80`) has no generated typed token;
this constant provides a named, searchable alternative.

-}
text_white_80 : Tailwind
text_white_80 =
    Tailwind "text-white/80"


{-| White text at 90 % opacity.
-}
text_white_90 : Tailwind
text_white_90 =
    Tailwind "text-white/90"


{-| Brand text at 50 % opacity.
-}
text_brand_50 : Tailwind
text_brand_50 =
    Tailwind "text-brand/50"


{-| Brand text at 70 % opacity.
-}
text_brand_70 : Tailwind
text_brand_70 =
    Tailwind "text-brand/70"


{-| Brand text at 80 % opacity.
-}
text_brand_80 : Tailwind
text_brand_80 =
    Tailwind "text-brand/80"


{-| Transparent background — used to reset browser default button backgrounds.
-}
bg_transparent : Tailwind
bg_transparent =
    Tailwind "bg-transparent"


{-| `currentColor` background — inherits text colour for SVG fill etc.
-}
bg_current : Tailwind
bg_current =
    Tailwind "bg-current"


{-| Black background at 50 % opacity — modal/dialog backdrop.
-}
bg_black_50 : Tailwind
bg_black_50 =
    Tailwind "bg-black/50"


{-| Brand background at 5 % opacity.
-}
bg_brand_5 : Tailwind
bg_brand_5 =
    Tailwind "bg-brand/5"


{-| Brand background at 10 % opacity.
-}
bg_brand_10 : Tailwind
bg_brand_10 =
    Tailwind "bg-brand/10"


{-| Brand background at 15 % opacity.
-}
bg_brand_15 : Tailwind
bg_brand_15 =
    Tailwind "bg-brand/15"


{-| Brand background at 20 % opacity.
-}
bg_brand_20 : Tailwind
bg_brand_20 =
    Tailwind "bg-brand/20"


{-| Brand-red background at 10 % opacity.
-}
bg_brand_red_10 : Tailwind
bg_brand_red_10 =
    Tailwind "bg-brand-red/10"


{-| Brand-red background at 15 % opacity.
-}
bg_brand_red_15 : Tailwind
bg_brand_red_15 =
    Tailwind "bg-brand-red/15"


{-| Brand-yellow background at 20 % opacity.
-}
bg_brand_yellow_20 : Tailwind
bg_brand_yellow_20 =
    Tailwind "bg-brand-yellow/20"


{-| Black border at 10 % opacity — subtle outline for colour swatches.
-}
border_black_10 : Tailwind
border_black_10 =
    Tailwind "border-black/10"


{-| Brand border at 30 % opacity.
-}
border_brand_30 : Tailwind
border_brand_30 =
    Tailwind "border-brand/30"


{-| Brand border at 40 % opacity.
-}
border_brand_40 : Tailwind
border_brand_40 =
    Tailwind "border-brand/40"


{-| Top border in the brand colour.
-}
border_t_brand : Tailwind
border_t_brand =
    Tailwind "border-t-brand"


{-| Top border in gray-900 — used for dark decorative accents.
-}
border_t_gray_900 : Tailwind
border_t_gray_900 =
    Tailwind "border-t-gray-900"


{-| Transparent border — reserves border space without showing colour.
-}
border_transparent : Tailwind
border_transparent =
    Tailwind "border-transparent"


{-| White border at 10 % opacity — subtle divider on dark backgrounds.
-}
border_white_10 : Tailwind
border_white_10 =
    Tailwind "border-white/10"


{-| Tailwind `group` utility — marks a parent so child `group-*` variants apply.
-}
group : Tailwind
group =
    Tailwind "group"


{-| Tailwind `peer` utility — marks a sibling so child `peer-*` variants apply.
-}
peer : Tailwind
peer =
    Tailwind "peer"


{-| Opt out of Tailwind Typography prose styles for a subtree.
-}
not_prose : Tailwind
not_prose =
    Tailwind "not-prose"


{-| Applies `text-inherit` to all direct `<p>` descendants via arbitrary variant.
-}
p_text_inherit : Tailwind
p_text_inherit =
    Tailwind "[&_p]:text-inherit"


{-| Removes vertical margin from all direct `<p>` descendants via arbitrary variant.
-}
p_my_0 : Tailwind
p_my_0 =
    Tailwind "[&_p]:my-0"


{-| Removes bullets from nested unordered lists via arbitrary variant.
-}
ul_list_none : Tailwind
ul_list_none =
    Tailwind "[&_ul]:list-none"


{-| Removes left padding from nested unordered lists via arbitrary variant.
-}
ul_pl_0 : Tailwind
ul_pl_0 =
    Tailwind "[&_ul]:pl-0"


{-| Removes outer vertical margin from nested unordered lists via arbitrary variant.
-}
ul_my_0 : Tailwind
ul_my_0 =
    Tailwind "[&_ul]:my-0"


{-| Adds vertical spacing between nested list items via arbitrary variant.
-}
ul_space_y_2 : Tailwind
ul_space_y_2 =
    Tailwind "[&_ul]:space-y-2"


{-| Makes nested list items flex containers via arbitrary variant.
-}
li_flex : Tailwind
li_flex =
    Tailwind "[&_li]:flex"


{-| Vertically centers nested list item contents via arbitrary variant.
-}
li_items_center : Tailwind
li_items_center =
    Tailwind "[&_li]:items-center"


{-| Adds horizontal gap between nested list marker and text via arbitrary variant.
-}
li_gap_2 : Tailwind
li_gap_2 =
    Tailwind "[&_li]:gap-2"


{-| Prepends a checkmark to nested list items via arbitrary variant.
-}
li_before_content_check : Tailwind
li_before_content_check =
    Tailwind "[&_li]:before:content-['✓']"


{-| Colors nested list item checkmarks with brand yellow via arbitrary variant.
-}
li_before_text_brand_yellow : Tailwind
li_before_text_brand_yellow =
    Tailwind "[&_li]:before:text-brand-yellow"


{-| Sets all inset edges to 0 (position: absolute fill).
-}
inset_0 : Tailwind
inset_0 =
    Tailwind "inset-0"


{-| Sets vertical inset (top + bottom) to 0.
-}
inset_y_0 : Tailwind
inset_y_0 =
    Tailwind "inset-y-0"


{-| Positions element at `left: 0`.
-}
left_0 : Tailwind
left_0 =
    Tailwind "left-0"


{-| Positions element at `left: 0.125rem (2px)`.
-}
left_0_5 : Tailwind
left_0_5 =
    Tailwind "left-0.5"


{-| Positions element at `left: 0.5rem (8px)`.
-}
left_2 : Tailwind
left_2 =
    Tailwind "left-2"


{-| Positions element at `left: 50%` — used with `-translate-x-1/2` to centre.
-}
left_half : Tailwind
left_half =
    Tailwind "left-1/2"


{-| Positions element at `top: 0`.
-}
top_0 : Tailwind
top_0 =
    Tailwind "top-0"


{-| Positions element at `top: 0.125rem (2px)`.
-}
top_0_5 : Tailwind
top_0_5 =
    Tailwind "top-0.5"


{-| Positions element at `top: 0.5rem (8px)`.
-}
top_2 : Tailwind
top_2 =
    Tailwind "top-2"


{-| Positions element at `right: 0.5rem (8px)`.
-}
right_2 : Tailwind
right_2 =
    Tailwind "right-2"


{-| `margin-inline-start: 2rem (32px)` — logical-property equivalent of ml-8.
-}
ms_8 : Tailwind
ms_8 =
    Tailwind "ms-8"


{-| `margin-inline-start: 3rem (48px)` — logical-property equivalent of ml-12.
-}
ms_12 : Tailwind
ms_12 =
    Tailwind "ms-12"


{-| Line-height 1.5rem (24px).
-}
leading_6 : Tailwind
leading_6 =
    Tailwind "leading-6"


{-| Line-height 1.75rem (28px).
-}
leading_7 : Tailwind
leading_7 =
    Tailwind "leading-7"


{-| Line-height 2.5rem (40px).
-}
leading_10 : Tailwind
leading_10 =
    Tailwind "leading-10"


{-| No horizontal translation (`translateX(0)`).
-}
translate_x_0 : Tailwind
translate_x_0 =
    Tailwind "translate-x-0"


{-| Horizontal translation of 1.25rem (20px).
-}
translate_x_5 : Tailwind
translate_x_5 =
    Tailwind "translate-x-5"


{-| Horizontal translation of −50% — centres an element when combined with `left-1/2`.
-}
neg_translate_x_half : Tailwind
neg_translate_x_half =
    Tailwind "-translate-x-1/2"


{-| `margin-inline-start: -1.5rem` — pulls a list marker into the gutter.
-}
neg_start_6 : Tailwind
neg_start_6 =
    Tailwind "-start-6"


{-| Ring in the brand colour.
-}
ring_brand : Tailwind
ring_brand =
    Tailwind "ring-brand"


{-| Ring in the brand-yellow colour.
-}
ring_brand_yellow : Tailwind
ring_brand_yellow =
    Tailwind "ring-brand-yellow"


{-| Arbitrary grid template: `auto 1fr` — icon + text two-column layout.
-}
grid_cols_auto_1fr : Tailwind
grid_cols_auto_1fr =
    Tailwind "grid-cols-[auto_1fr]"


{-| Custom height of 8.75rem (140px) — matches the brand h-35 design token.
-}
h_35 : Tailwind
h_35 =
    Tailwind "h-35"


{-| Custom width of 8.75rem (140px) — matches the brand w-35 design token.
-}
w_35 : Tailwind
w_35 =
    Tailwind "w-35"


{-| Display / hero heading style — 3 rem, 700, lh 1.1.
-}
type_display : Tailwind
type_display =
    Tailwind "type-display"


{-| Page-level heading (H1) style — 1.875 rem, 700, lh 1.2.
-}
type_h1 : Tailwind
type_h1 =
    Tailwind "type-h1"


{-| Section heading (H2) style — 1.5 rem, 700, lh 1.3.
-}
type_h2 : Tailwind
type_h2 =
    Tailwind "type-h2"


{-| Sub-section heading (H3) style — 1.25 rem, 600, lh 1.35.
-}
type_h3 : Tailwind
type_h3 =
    Tailwind "type-h3"


{-| Card / widget heading (H4) style — 1.125 rem, 600, lh 1.4.
-}
type_h4 : Tailwind
type_h4 =
    Tailwind "type-h4"


{-| Default body text style — 1 rem, 400, lh 1.6.
-}
type_body : Tailwind
type_body =
    Tailwind "type-body"


{-| Small body / UI label style — 0.875 rem, 500, lh 1.5.
-}
type_body_small : Tailwind
type_body_small =
    Tailwind "type-body-small"


{-| Caption / footnote style — 0.875 rem, 400, lh 1.4, ls 0.02 em.
-}
type_caption : Tailwind
type_caption =
    Tailwind "type-caption"


{-| Monospace / code style — 0.875 rem, 400, lh 1.6.
-}
type_mono : Tailwind
type_mono =
    Tailwind "type-mono"


{-| Overline label style — 0.75 rem, 600, lh 1.4, ls 0.08 em, all-caps.
-}
type_overline : Tailwind
type_overline =
    Tailwind "type-overline"
